# file: nginx/tasks/modules/http_geoip_module.yml
# configure flag: --with-http_geoip_module

- name: Nginx | Modules | Install GeoIp lib
  apt: pkg={{ item }} state=latest
  with_items:
    - libgeoip1
    - libgeoip-dev

- name: Nginx | Modules | Create directory inside nginx
  sudo: yes
  file: path={{nginx_dir}}/geoip state=directory

- name: Nginx | Modules | Download GeoIP database files
  sudo: yes
  get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz dest={{nginx_dir}}/geoip/GeoIP.dat.gz

- name: Nginx | Modules | Download GeoLiteCity database files
  sudo: yes
  get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz dest={{nginx_dir}}/geoip/GeoLiteCity.dat.gz

- name: Nginx | Modules | Unarchive GeoIP files
  sudo: yes
  shell: gunzip -c {{nginx_dir}}/geoip/GeoIP.dat.gz > {{nginx_dir}}/geoip/GeoIP.dat

- name: Nginx | Modules | Unarchive GeoLiteCity files
  sudo: yes
  shell: gunzip -c {{nginx_dir}}/geoip/GeoLiteCity.dat.gz > {{nginx_dir}}/geoip/GeoLiteCity.dat
