# file: nginx/tasks/scripts.yml

- name: Nginx | Copy the nxensite and nxdissite scripts
  template:
    src: "{{item}}.j2"
    dest: "/usr/sbin/{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items: ["nxensite", "nxdissite"]
