# file: nginx/tasks/user.yml

- name: Nginx | Make sure the nginx group is present
  group:
    gid: "{{nginx_gid}}"
    name: "{{nginx_group}}"
    state: present

- name: Nginx | Make sure the www directory is present
  file:
    path: "{{nginx_www_dir}}"
    state: directory

- name: Nginx | Make sure the nginx user is present
  user:
    name: "{{nginx_user}}"
    uid: "{{nginx_uid}}"
    group: "{{nginx_group}}"
    comment: "Nginx user"
    home: "{{nginx_www_dir}}"
    shell: /bin/false
    state: present
    system: yes

- name: Nginx | Set the right directory permissions for the www directory
  file:
    path: "{{nginx_www_dir}}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    state: directory

- name: Nginx | Set the right expiration on the nginx user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{nginx_user}}"
